### ISSUE TITLE
User is allowed to send a tweet even if the tweet is empty

### ISSUE THREAD

**Issue by Surya97** [knowtheory/audience-mapper#42]
Though the tweet is not sent actually, "send tweet" button is still clickable even though the tweet is empty which shouldn't be allowed.

**Comment by knowtheory** [comment]
The app also shouldn't tell you a tweet was sent if the request to twitter fails.

**Comment by Surya97** [comment]
Fixed in this commit https://github.com/knowtheory/audience-mapper/commit/f97f6d5c9e2209d326aebbeb21c17c1b6ff1ff00
